### ISSUE TITLE
Custom Nunjucks environment w/ autoescape

### ISSUE THREAD

**Issue by pdehaan** [pdehaan/11ty-blog-ideas#7]
Per https://github.com/11ty/eleventy/issues/495#issuecomment-493939098,

Looks like instead of possibly using the `| safe` filter on 90% of the output, we might be able to fiddle with autoescape (but requires a custom Nunjucks environment):

```
  let nunjucksEnvironment = new Nunjucks.Environment(
    new Nunjucks.FileSystemLoader(["src/site/_templates"]), // we need to pass in our includes dir here
    { 
      lstripBlocks: true,
      trimBlocks: true,
      autoescape: false
     });

  nunjucksEnvironment.addGlobal(name, nunjucksGlobals[name]);

  eleventyConfig.setLibrary("njk", nunjucksEnvironment);
```

See:
- https://mozilla.github.io/nunjucks/api.html#opts-autoescape
- https://mozilla.github.io/nunjucks/templating.html#autoescaping
- https://mozilla.github.io/nunjucks/templating.html#safe
- https://mozilla.github.io/nunjucks/templating.html#escape-aliased-as-e

**Comment by pdehaan** [comment]
Done. See https://github.com/pdehaan/11ty-nunjucks-config

Also filed https://github.com/11ty/eleventy/issues/895 since this was trickier than expected.

**Comment by einomi** [comment]
```
Done. See https://github.com/pdehaan/11ty-nunjucks-config

Also filed 11ty/eleventy#895 since this was trickier than expected.
```

@pdehaan when I add a config as in https://github.com/pdehaan/11ty-nunjucks-config, 11ty stops compiling .njk files on change

**Comment by pdehaan** [comment]
@einomi are you saying the custom nunchucks environment works, but the `eleventy —watch` behavior breaks?

**Comment by einomi** [comment]
@pdehaan yeah, it looks like it doesn't recompile the .njk files when I edit them. However, browsersync reloads the page but the content is not updated on it.

**Comment by pdehaan** [comment]
@einomi Interesting, if that's still happening in latest 0.12.1 (i think my sample repo above had an older version of Eleventy), I'd file a bug at https://github.com/11ty/eleventy/issues.

In the meantime, you could see if a custom watch target for your nunjucks template folder works: https://www.11ty.dev/docs/watch-serve/#add-your-own-watch-targets

I generally don't use `--watch` and just rebuild manually, so I'm not very knowledgeable on all things related to watching and rebuilding.
